SELECT ID_CURSO, DATA_INICIO, DATA_TERMINO, LOGIN_CADASTRO FROM Turmas
WHERE ID_CURSO = (SELECT ID_CURSO FROM Cursos WHERE NOME_CURSO = 'Python');

UPDATE Turmas SET LOGIN_CADASTRO = 'TesteUpdate'
WHERE ID_CURSO = (SELECT ID_CURSO FROM Cursos WHERE NOME_CURSO = 'C++');

SELECT * FROM Turmas;

DELETE Turmas
WHERE ID_CURSO = (SELECT ID_CURSO FROM Cursos WHERE NOME_CURSO = 'C#');

SELECT * FROM Turmas INNER JOIN Cursos ON Cursos.ID_CURSO = Turmas.ID_CURSO;
