SELECT SUM(Alunos_Turmas.VALOR) Soma_Valores FROM Alunos_Turmas;

SELECT c.NOME_CURSO, SUM(at.VALOR_DESCONTO) DESCONTOS FROM Alunos a
INNER JOIN Alunos_Turmas at ON a.ID_ALUNO = at.ID_ALUNO
INNER JOIN Turmas t ON at.ID_TURMA = t.ID_TURMA
INNER JOIN Cursos c ON t.ID_CURSO = c.ID_CURSO
GROUP BY c.NOME_CURSO;

SELECT COUNT(Cursos.NOME_CURSO) Qtd_Cursos FROM Cursos;

SELECT Cursos.NOME_CURSO, COUNT(Cursos.NOME_CURSO) Qtd_Cursos FROM Cursos
GROUP BY NOME_CURSO;

SELECT at.ID_TURMA, COUNT(*) MATRICULAS FROM Alunos a
INNER JOIN Alunos_Turmas at ON at.ID_ALUNO = a.ID_ALUNO
GROUP BY at.ID_TURMA;
