CREATE TABLE Alunos (
ID_ALUNO INT PRIMARY KEY NOT NULL,
NOME VARCHAR(150) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
SEXO VARCHAR(1),
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);

CREATE TABLE Situacao (
ID_SITUACAO INT PRIMARY KEY NOT NULL,
SITUACAO VARCHAR(25) NOT NULL,
DATA_CADASTRO DATETIME,
LOGIN_CADASTRO VARCHAR(15));

CREATE TABLE Cursos (
ID_CURSO INT PRIMARY KEY NOT NULL,
NOME_CURSO VARCHAR(200) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);
  
CREATE TABLE Turmas (
ID_TURMA INT PRIMARY KEY NOT NULL,
ID_ALUNO INT NOT NULL,
ID_CURSO INT NOT NULL,
VALOR_TURMA NUMERIC(15, 2) NOT NULL,
DESCONTO NUMERIC(3, 2) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_TERMINO DATE,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15));
  
CREATE TABLE Registro_Presenca (
ID_TURMA INT NOT NULL,
ID_ALUNO INT NOT NULL,
ID_SITUACAO INT NOT NULL,
DATA_PRESENCA DATE NOT NULL,
DATA_CADASTRO DATE NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);

/* DROP TABLE Alunos
DROP TABLE Cursos
DROP TABLE Registro_Presenca
DROP TABLE Situacao
DROP TABLE Turmas */

ALTER TABLE Turmas
ADD CONSTRAINT FK_Alunos FOREIGN KEY (ID_ALUNO) REFERENCES Alunos (ID_ALUNO);

ALTER TABLE Turmas
ADD CONSTRAINT FK_Cursos FOREIGN KEY (ID_CURSO) REFERENCES Cursos (ID_CURSO);

ALTER TABLE Registro_Presenca
ADD CONSTRAINT FK_TurmasRP FOREIGN KEY (ID_TURMA) REFERENCES Turmas (ID_TURMA);

ALTER TABLE Registro_Presenca
ADD CONSTRAINT FK_AlunosRP FOREIGN KEY (ID_ALUNO) REFERENCES Alunos (ID_ALUNO);

ALTER TABLE Registro_Presenca
ADD CONSTRAINT FK_SituacaoRP FOREIGN KEY (ID_SITUACAO) REFERENCES Situacao (ID_SITUACAO);

SELECT * FROM dbo.Alunos;
INSERT INTO dbo.Alunos (ID_ALUNO, NOME, DATA_NASCIMENTO, SEXO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (1, 'João Batista', '04/09/1990', 'M', '10/10/2025', 'JOAOB');

SELECT * FRom dbo.Alunos;
INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (1, 'SQL Server', '10/10/2025', 'SQL1');

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (2, 'Oracle', '10/10/2025', 'ORACLE1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (1, 'Presença Confirmada', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (2, 'Falta Justificada', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (3, 'Falta Injustificada', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (4, 'Atestado Médico', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (5, 'Licença Médica', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (6, 'Férias', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (7, 'Atestado de Ocorrência', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (8, 'Exame Médico', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (9, 'Provação de Conhecimento', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (10, 'Ausência', '10/10/2025', 'Teste1');

SELECT * FROM dbo.Situacao;
ALTER TABLE Turmas DROP CONSTRAINT FK_Alunos;

ALTER TABLE Turmas DROP COLUMN id_aluno;

ALTER TABLE Turmas DROP COLUMN Valor_Turma;

ALTER TABLE Turmas DROP COLUMN DESCONTO;

CREATE TABLE Alunos_Turmas (
ID_TURMA INT NOT NULL,
ID_ALUNO INT NOT NULL,
VALOR NUMERIC (13, 2) NOT NULL,
VALOR_DESCONTO NUMERIC (3, 2) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);
  
ALTER TABLE Alunos_Turmas
ADD CONSTRAINT FK_Turma FOREIGN KEY (ID_TURMA) REFERENCES Turmas(ID_TURMA);
ALTER TABLE Alunos_Turmas
ADD CONSTRAINT FK_Aluno FOREIGN KEY (ID_ALUNO) REFERENCES Alunos(ID_ALUNO);

INSERT INTO Turmas (ID_TURMA, ID_CURSO, DATA_INICIO, DATA_TERMINO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (1, 1, '25/10/2025', '01/11/2026' GETDATE(), 'Teste1');

INSERT INTO Turmas (ID_TURMA, ID_CURSO, DATA_INICIO, DATA_TERMINO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (2, 2, '01/11/2025', '01/12/2026' GETDATE(), 'Teste1');

INSERT INTo Alunos_Turmas (ID_TURMA, ID_ALUNO, VALOR, VALOR_DESCONTO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (1, 10, 1200, 0.1, GETDATE(), 'Teste123');
